language: ruby

sudo: false

rvm:
  - 2.2.2
  - 2.6.2
  - 2.6.6

gemfile:
  - Gemfile

env:
  global:
    - CI="travis"
  matrix:
    - MONGODB=2.6.11
    - MONGODB=3.0.7
    - MONGODB=3.2.0-rc3
    - MONGODB=4.4.2

before_install:
  - gem update rake

before_script:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz -O /tmp/mongodb.tgz
  - tar -xvf /tmp/mongodb.tgz
  - mkdir /tmp/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath /tmp/data --bind_ip 127.0.0.1 --noauth &> /dev/null &

notifications:
  email: true
